### ISSUE TITLE
Czech Translation

### ISSUE THREAD

**Issue by IneffableKoD** [IneffableKoD/cov19testmap#2]
Since I mapped all Czech testing facilities, it would be helpful to translate the page to Czech.

**Comment by ivoban** [comment]
Happy to do that

**Comment by IneffableKoD** [comment]
Great! We should also think about how we structure it in a useful way (language button, separately, filter).

**Comment by ivoban** [comment]
yes, or translation files, and load on demand the texts ... etc.

**Comment by IneffableKoD** [comment]
> yes, or translation files, and load on demand the texts ... etc.

Feel free to make a proposal regarding that.

**Comment by IneffableKoD** [comment]
Language support added.
