### ISSUE TITLE
Fix data entires overlapping popup

### ISSUE THREAD

**Issue by IneffableKoD** [IneffableKoD/cov19testmap#31]
Some data entries (websites mostly) overlap the popup on the map (see screenshot below).

<img width="942" alt="Screen Shot 2020-04-12 at 20 14 23" src="https://user-images.githubusercontent.com/34814092/79076419-46388980-7cfa-11ea-91a1-25da654ceeb5.png">

**Comment by elolelo** [comment]
@IneffableKoD you can assign this issue to me. 

By the way, are you Ok with covid19za adding this link to your map  on the repo home page?

**Comment by IneffableKoD** [comment]
Assigned, thank you!

Absolutely, please feel free to add it. 

P.s. I sent an email to you.

**Comment by elolelo** [comment]
@IneffableKoD  I have submitted a pull request to fix this.

 I've seen the email and replied. 
Thank you
